defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  pool: 5
  host: mysql


test: &test
  <<: *defaults
  database: timestack_test

development:
  <<: *defaults
  database: <%= ENV['DATABASE'] %> 


cucumber:
  <<: *test
