defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: yasser
  password: rsi1111
  pool: 5
  host: localhost


test: &test
  <<: *defaults
  database: timestack_test

development:
  <<: *defaults
  database: timestack


cucumber:
  <<: *test
